{% set version = "0.3.1" %}
{% set build = "002" %}

package:
    name: r-rgcca-launcher
    version: {{ version }}
source:
    git_rev: {{ version }}
    git_url: https://github.com/BrainAndSpineInstitute/rgcca_Rpackage.git
build:
    noarch: generic
    number: {{ build }}
    rpaths:
        - lib/
        - lib/R/lib/
    string: r35_{{ build }}
requirements:
    host:
        - _r-mutex
        - r-base
        - r-deriv
        - r-devtools
        - r-mass
        - r-rgcca
        - r-ggplot2
        - r-optparse
        - r-scales
        - r-igraph
        - r-ggrepel
        - r-plotly
        - r-visnetwork
        - libgfortran
    run:
        - r-deriv
        - r-mass
        - r-rgcca
        - r-ggplot2
        - r-optparse
        - r-scales
        - r-igraph
        - r-ggrepel
        - r-plotly
        - r-visnetwork
        - libgfortran

test:
    commands:
        - cd ${PREFIX} && Rscript R/launcher.R -h
about:
    home: https://CRAN.R-project.org/package=RGCCA
    license: GPL (>= 2)
    license_family: GPL3
    summary: 'Multiblock data analysis concerns the analysis of several sets of variables
        (blocks) observed on the same group of individuals. The main aims of the RGCCA
        package are: (i) to study the relationships between blocks and (ii) to identify
        subsets of variables of each block which are active in their relationships
        with the other blocks.'
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        -ecamenen
#app:
#    entry: cd $CONDA_PREFIX && Rscript R/launcher.R